version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: _docker/web.docker
        restart: always
        volumes:
            - ./:/var/www/html
        ports:
            - "8099:80"
        links:
            - app
        environment:
            - NGINX_HOST=puphpet.docker www.puphpet.docker
            - NGINX_PORT=80
    app:
        build:
            context: ./
            dockerfile: _docker/app.docker
        restart: always
        volumes:
            - ./:/var/www/html
